import { useState } from 'react';
import { motion } from 'framer-motion';
import { useTheme } from '../../context/ThemeContext';
import SectionWrapper from '../SectionWrapper';
import ScrollReveal from '../ScrollReveal';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus, vs } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { FiCopy, FiCheck, FiChevronDown, FiChevronUp } from 'react-icons/fi';

const fullJson = `{
  "title": "The Rickshaw Accident",
  "seed_story": {
    "title": "The Rickshaw Accident",
    "description": "Late afternoon on Shahrah-e-Faisal near Karachi Airport. Rush hour traffic. Hot and humid. A rickshaw and a car have collided, both drivers blaming each other."
  },
  "events": [
    {
      "type": "narration",
      "content": "Saleem, the rickshaw driver, is the most likely to break the silence...",
      "turn": 0
    },
    {
      "type": "dialogue",
      "speaker": "Saleem",
      "content": "Arre yaar! Dekho toh, dekho! Yeh banda full speed mein aaya!",
      "turn": 1
    },
    {
      "type": "dialogue",
      "speaker": "Ahmed Malik",
      "content": "Five people's stomachs? Is that my concern? Look at my vehicle!",
      "turn": 2
    },
    {
      "type": "dialogue",
      "speaker": "Constable Raza",
      "content": "Acha, acha, shant ho jao. Paperwork hoga...",
      "turn": 3
    },
    {
      "type": "dialogue",
      "speaker": "Uncle Jameel",
      "content": "Kya nautanki hai yeh? System hai, system!",
      "turn": 5
    },
    {
      "type": "dialogue",
      "speaker": "Constable Raza",
      "content": "Five hazaar. Bas. Five hazaar de dijiyega.",
      "turn": 7
    },
    {
      "type": "narration",
      "content": "Five thousand rupees exchanged hands. Life in Karachi continued...",
      "turn": 7,
      "metadata": { "conclusion": true }
    }
  ],
  "metadata": {
    "total_turns": 7,
    "conclusion_reason": "Financial settlement reached between parties."
  }
}`;

const sections = [
  { label: 'metadata', start: 1, end: 5, color: '#82B1FF' },
  { label: 'events', start: 6, end: 37, color: '#D500F9' },
  { label: 'conclusion', start: 38, end: 42, color: '#69F0AE' },
];

export default function JsonOutput() {
  const { isDark } = useTheme();
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(true);

  const handleCopy = () => {
    navigator.clipboard.writeText(fullJson);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <SectionWrapper id="json-output" dark>
      <ScrollReveal>
        <div className="text-center mb-12">
          <h2 className={`text-4xl sm:text-5xl font-bold mb-4 ${isDark ? 'text-white' : 'text-gray-900'}`}>
            JSON <span className="text-gradient">Output</span>
          </h2>
          <p className={`text-lg max-w-2xl mx-auto ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>
            The structured story output generated by the system
          </p>
        </div>
      </ScrollReveal>

      {/* Section highlights */}
      <ScrollReveal>
        <div className="flex flex-wrap justify-center gap-3 mb-8">
          {sections.map(sec => (
            <div key={sec.label} className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full" style={{ backgroundColor: sec.color }} />
              <span className={`text-sm font-mono ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>{sec.label}</span>
            </div>
          ))}
        </div>
      </ScrollReveal>

      <ScrollReveal>
        <div className="max-w-4xl mx-auto">
            <div className={`rounded-2xl overflow-hidden ${isDark ? 'card-dark' : 'card-light'}`}>
            {/* Header */}
            <div className={`flex items-center justify-between px-4 py-2 ${isDark ? 'bg-dark-card' : 'bg-gray-100'}`}>
              <div className="flex items-center gap-2">
                <div className="w-3 h-3 rounded-full bg-red-500/80" />
                <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                <div className="w-3 h-3 rounded-full bg-green-500/80" />
                <span className={`text-xs ml-2 font-mono ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>story_output.json</span>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setExpanded(!expanded)}
                  className={`flex items-center gap-1 text-xs px-2 py-1 rounded ${isDark ? 'text-gray-400 hover:text-white' : 'text-gray-500 hover:text-gray-900'} transition`}
                >
                  {expanded ? <><FiChevronUp size={12} /> Collapse</> : <><FiChevronDown size={12} /> Expand</>}
                </button>
                <button
                  onClick={handleCopy}
                  className={`flex items-center gap-1 text-xs px-2 py-1 rounded ${isDark ? 'text-gray-400 hover:text-white' : 'text-gray-500 hover:text-gray-900'} transition`}
                >
                  {copied ? <><FiCheck size={12} /> Copied</> : <><FiCopy size={12} /> Copy</>}
                </button>
              </div>
            </div>

            <motion.div
              animate={{ height: expanded ? 'auto' : 100 }}
              className="overflow-hidden relative"
            >
              <SyntaxHighlighter
                language="json"
                style={isDark ? vscDarkPlus : vs}
                showLineNumbers
                customStyle={{
                  margin: 0,
                  padding: '1.5rem',
                  fontSize: '0.8rem',
                  background: isDark ? '#1E1E2E' : '#FAFAFA',
                  maxHeight: expanded ? 'none' : '100px',
                }}
              >
                {fullJson}
              </SyntaxHighlighter>

              {!expanded && (
                <div className={`absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t ${isDark ? 'from-dark-surface' : 'from-light-surface'}`} />
              )}
            </motion.div>
          </div>
        </div>
      </ScrollReveal>
    </SectionWrapper>
  );
}
